# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-06 03:06
from __future__ import unicode_literals

from django.db import migrations, models

import rest_models.storage


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True)),
                ('photo', models.ImageField(null=True, storage=rest_models.storage.RestApiStorage(), upload_to='')),
            ],
        ),
    ]
