# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-16 05:20
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.contrib.gis.db.models import PointField
from django.db import migrations, models

import testapi.models
from testapi.models import POSTGIS, has_jsonfield


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=135)),
            ] + ([('location', PointField(blank=True, null=True, srid=4326))] if POSTGIS else [])
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=135)),
                ('code', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('price', models.FloatField()),
                ('from_date', models.DateField(auto_now_add=True)),
                ('to_date', models.DateTimeField(default=testapi.models.auto_now_plus_5d)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('menu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pizzas', to='testapi.Menu')),
            ],
        ),
        migrations.CreateModel(
            name='PizzaGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='testapi.PizzaGroup')),
                ('pizzas', models.ManyToManyField(related_name='groups', to='testapi.Pizza')),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('cost', models.FloatField()),
            ] + ([('metadata', django.contrib.postgres.fields.jsonb.JSONField(null=True))] if has_jsonfield else []),
        ),
        migrations.AddField(
            model_name='pizza',
            name='toppings',
            field=models.ManyToManyField(blank=True, related_name='pizzas', to='testapi.Topping'),
        ),
    ]
