name: Publish

on:
  release:
    types:
      - published

jobs:
  build-publish:
    name: Build distribution and publish to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/django-rest-models
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - uses: actions/checkout@v4
      - name: Setup python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install build lib
        run: pip install build
      - name: Build wheel and source
        run: python3 -m build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
